[[project]]
name = "京大院試数学解答"
desc = "京大の数学系の院の, 院試の問題の解答例PDF. 当時蔓延していた有料の解答を駆逐するために作成しました．"
tags = ["math", "pdf", "tex"]
links = [
  { name = "GitHub", url = "https://github.com/Seasawher/graduate_exam" },
]

[[project]]
name = "Mathematics in Type Theory 日本語訳"
desc = "集合論ではなく，型理論をベースに数学を行うということがどういうことか，数学を知っている人向けにわかりやすく説明したブログ記事を，著者の許可を得て日本語訳したものです．"
tags = ["math", "lean", "mdbook", "lean-ja", "github-pages"]
links = [
  { name = "GitHub", url = "https://github.com/lean-ja/math-in-type-theory-ja" },
  { name = "Website", url = "https://lean-ja.github.io/math-in-type-theory-ja/" },
]

[[project]]
name = "lean-ja トップページ"
desc = "Lean 言語の日本語コミュニティ lean-ja のウェブサイトです．Zola で制作し，GitHub Pages にデプロイしています．ロゴは lean-ja のメンバーの方に作っていただきました．"
tags = ["lean", "lean-ja", "zola", "juice", "github-pages"]
links = [
  { name = "GitHub", url = "https://github.com/lean-ja/lean-ja.github.io" },
  { name = "Website", url = "https://lean-ja.github.io/" },
]

[[project]]
name = "Lean4 タクティク逆引きリスト"
desc = "普段の数学を Lean にどう翻訳するのかイメージできるように, Lean でよく使うタクティクを使用場面から逆引きできるようにまとめたリストです．GitHub Action を使って，Lean のコード例のコンパイルが通ることを自動的に検証する CI が組んであります．"
tags = ["lean", "lean-ja", "mdbook", "github-pages"]
links = [
  { name = "GitHub", url = "https://github.com/lean-ja/tactic-cheetsheet" },
  { name = "Website", url = "https://lean-ja.github.io/tactic-cheetsheet/" },
]
